spring:
  main:
    allow-circular-references: true
  profiles:
    active: prod
  application:
    name: My-Navigation-Admin
  datasource:
    username: ${one.moonx.datasource.username}
    password: ${one.moonx.datasource.password}
    url: jdbc:mysql://${one.moonx.datasource.host}:${one.moonx.datasource.port}/${one.moonx.datasource.database}?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: ${one.moonx.datasource.driver-class-name}
    hikari:
      max-lifetime: 300000
  sql:
    init:
      continue-on-error: true
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  data:
    redis:
      host: ${one.moonx.redis.host}
      port: ${one.moonx.redis.port}
      password: ${one.moonx.redis.password}
      database: ${one.moonx.redis.database}

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: one.moonx.navigation.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    use-column-label: true

server:
  port: ${one.moonx.server.port}
one:
  moonx:
    jwt:
      adminSecretKey: ${one.moonx.jwt.adminSecretKey}
      adminTtl: ${one.moonx.jwt.adminTtl}
      adminTokenName: ${one.moonx.jwt.adminTokenName}